{-# LANGUAGE TemplateHaskell #-}

import Control.Monad
import Data.List(sort)
import Data.Default
import Control.Monad.Trans.Free
import Control.Monad.Trans.State
import Control.Lens hiding (Level)
import Types
import Generators
import Game

makeLenses ''Player
makeLenses ''Room
makeLenses ''Level
makeLenses ''GameState

-- a simple test room
testRoom :: Room
testRoom =  rType    .~ KaliAltar 
          $ entities .~ [( (L, D) , Enemy' Spider ), ( (M, D), Player' p )] 
          $ def :: Room
  where p = holding .~ ( Just (GroundItem' PotEmpty) ) 
          $ items   .~ [ClimbingGloves] 
          $ def :: Player
          
main = do
  -- | This will be generated by a seed
  let g = undefined :: GameState
  -- | Discard this computation, because the result doesn't matter.
  -- | All work is done in (Game.hs), see that file for notes.
  runFreeT $ evalStateT game g -- IO (Something Complicated)
